name: gonzo
channels:
- conda-forge
- conda-forge/label/fenics-dev
- bioconda
- jorgenriseth
- nodefaults
dependencies:
- snakemake >=8.27.1,<9
- snakemake-executor-plugin-cluster-generic
- svmtk >=1.3.0,<2
- fenics >=2019.1.0,<2020
- h5py >=3.12.1,<4
- dcm2niix >=1.0.20241211,<2
- numpy >=1.26.4,<2
- matplotlib >=3.10.0,<4
- pydantic-settings >=2.7.1,<3
- jupyter >=1.1.1,<2
- python >=3.9,<3.12
- pantarei >=0.6.2
- mpi4py
- openmpi
- pip
- pip:
  - git+https://github.com/jorgenriseth/gMRI2FEM.git
